" Add your custom abbreviations here&(FILENAME=.vimrc)

nnoremap <leader>gt    :b %(name).tex<Cr>
nnoremap <F6>          :call F%(name)Show()<CR>
nnoremap <F7>          :call F%(name)Make()<CR>

function! F%(name)Make()
    call feedkeys(':SlimeSend1 make ', 'n')
endfunction

function! F%(name)Show()
    call feedkeys(':SlimeSend1 gnome-open %(name).pdf ', 'n')
endfunction
