#! /usr/bin/python3
# ----------------------------------------------------------------------------
# File    : %(class|class name).py
# Author  : %(author)
# Created : $(date '+%m/%d/%y')
# ----------------------------------------------------------------------------
#
# Add a description here.&(FILENAME=$(echo $class).py)
#
# ----------------------------------------------------------------------------

class $(echo $class):

    def __init__( self ):
        pass
