#!/usr/bin/env python3
#coding: utf-8
"""
Unit tests for the %(module|name of tested module) module.
"""&(FILENAME=test_%(module).py)

import unittest

class test_%(module)(unittest.TestCase):

    def test_dummy(self):
        self.fail("Not yet implemented")


if __name__ == "__main__":
    unittest.main()
