#! /bin/bash
# ----------------------------------------------------------------------------
# File    : %(name).sh&(FILENAME=$(echo $name).sh)
# Author  : %(author)
# Created : $(date '+%m/%d/%y')
# ----------------------------------------------------------------------------
# 
# Add a description here
#
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# FUNCTION debug( str )
#
# Outputs the specified string if, and only if the global symbol $DEBUG is set
# to "true"
# ----------------------------------------------------------------------------
DEBUG=true
function debug
{
        if [ "$DEBUG" == true ]
        then
            echo "[DEBUG] $1"
        fi
}

# ----------------------------------------------------------------------------
# FUNCTION main( ... )
#
# Scripts main function.
# ----------------------------------------------------------------------------
function main
{
        echo "Hello World!"       
}

main "$@"
